-- add the article tables
create table if not exists budgets
(
    id          bigint generated by default as identity,
    name        varchar     not null default '',
    amount      bigint      not null default 0,
    description varchar     not null default '',
    user_id     bigint      not null references users (id) on delete cascade,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp
);

-- alter table budgets
--     add constraint budgets_id_pk primary key (id);
