-- add the article tables
-- drop type if exists time_frequency;

-- create type time_frequency as ENUM (
--   'Daily','Weekly','Monthly','Qaurterly','Annually'
--   );

create table if not exists budgets
(
    id          bigint generated by default as identity,
    name        varchar     not null default '',
    amount      float      not null default 0.00,
    description varchar     not null default '',
    frequency   varchar    not null default 'Monthly',
    user_id     bigint      not null references users (id) on delete cascade,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp,
    deleted_at timestamptz default null
    
);

alter table budgets
    add constraint budgets_id_pk primary key (id);
