-- Add migration script here

create table if not exists sessions
(
    id          bigint generated by default as identity,
    exp         timestamptz      not null,
    user_id     bigint           not null references users (id) on delete cascade,
    user_agent  varchar          not null default ''
);

alter table sessions
    add constraint sessions_id_pk primary key (id);
