-- add the article tables
drop type if exists ledger_category;
drop type if exists ledger_type;

create type ledger_category as ENUM ('essential','non_essential');
create type ledger_type as ENUM ('income','expense');
-- create type if not exists ledger_periodical as ENUM ("DAILY","WEEKLY","MONTHLY","QUARTERLY","ANNUAL");


create table if not exists ledgers
(
    id          bigint generated by default as identity,
    name        varchar     not null default '',
    amount      float         not null default 0.00,
    description varchar     not null default '',
    type        ledger_type ,
    category    ledger_category not null default 'non_essential',
    user_id     bigint      not null references users (id) on delete cascade,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp,
    deleted_at timestamptz default null
);

alter table ledgers
    add constraint ledgers_id_pk primary key (id);
