-- add the article tables
drop type if exists category_type;

create type category_type as ENUM (
  'Essential','Non_Essential'
  );

create table if not exists categories
(
    id          bigint generated by default as identity,
    name        varchar     not null default '',
    type        category_type not null default 'Non_Essential',
    user_id     bigint      not null references users (id) on delete cascade,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp,
    deleted_at  timestamptz default null
);

alter table categories
  add constraint categories_id_pk primary key (id);
