-- add the article tables
-- drop type if exists ledger_category;
-- drop type if exists ledger_type;

-- create type ledger_category as ENUM (
--   'Essential','Non_Essential'
-- );
-- create type ledger_type as ENUM (
--   'Income','Expense'
-- );

create table if not exists ledgers
(
    id          bigint generated by default as identity,
    name        varchar     not null default '',
    amount      float         not null default 0.00,
    description varchar     not null default '',
    type        varchar not null default 'Expense',
    category    varchar not null default 'Non_Essential',
    user_id     bigint      not null references users (id) on delete cascade,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp,
    deleted_at timestamptz default null
);

alter table ledgers
    add constraint ledgers_id_pk primary key (id);
