import { DashboardSideBar } from "@/components/DashboardSideBar";

export const metadata = {
  title: "Budgetto - Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex w-full h-screen">
      <DashboardSideBar />
      <div className="flex-1">
        <header>Dashboard</header>
        <main>{children}</main>
      </div>
    </section>
  );
}
