import { DashboardHeader } from "@/components/DashboardHeader";
import { DashboardSideBar } from "@/components/DashboardSideBar";

export const metadata = {
  title: "Budgetto - Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex overflow-hidden w-full h-screen">
      <DashboardSideBar />
      <div className="flex-1">
        <DashboardHeader />
        <main className="overflow-y-scroll h-full">{children}</main>
      </div>
    </section>
  );
}
